### ISSUE TITLE
Option to use `url` from configuration file if not passed as ENV variable

### ISSUE THREAD

**Issue by debussyman** [extragoodlabs/jwctl#2]
The cli requires the host url to be passed in as an environment variable. It would be more convenient if this could be stored as a local file, similar to the token.

For example, it could be written to $HOME/.config/jwctl/.host

**Comment by debussyman** [comment]
I see now that there is already an option for a local `config.yaml` file

**Comment by hexedpackets** [comment]
We do need to make it clearer how to set the config initially, which will be done as part of #1.
